# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

matrix:
  os:
    - linux
    - osx
  r:
    - release
    - devel
  env:
    - R_XTRA_CXXFLAGS = -DARMA_64BIT_WORD
    - R_XTRA_CXXFLAGS = -DARMA_32BIT_WORD
  r_check_args:
    -
    - --use-valgrind

cache: packages

env:
  global:
  - OS=$(uname -s)

cran: http://cran.rstudio.com

r_packages:
  - covr
  - ggforce
  - ggplot2

r_binary_packages:
  - testthat
  - png
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - dbscan
  - knitr
  - rmarkdown

sudo: required

before_install: |
  mkdir ~/.R
  cat <<EOF >> ~/.R/Makevars
  CXX1X=g++-4.9
  FC=gfortran-4.9
  CXX1XSTD=-std=c++11

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - valgrind
      - libudunits2-dev
  brew_packages:
      - udunits

after_success:
  - Rscript -e 'covr::codecov(branch = Sys.getenv("TRAVIS_BRANCH"))'
